### ISSUE TITLE
[Bug]: Extended enum exported multiple times produces build issues

### ISSUE THREAD

**Issue by remi-amadeus** [AmadeusITGroup/otter#1028]
### Package name

schematics

### Package version

9.3.5

### Reproduction steps

Override an existing model enum using allOf in the spec

allOf:
      - $ref: '#/definitions/_MyEnumModel'
      - type: object
        discriminator: xxx
        properties:
          xxxType:
            type: string
            description: >
              description
            enum:
              - Value1
              - Value2
              - Value3

### Current result

Enum files generated are having conflicts between each other (between the initial Enum and the extended Enum the the exports level) while trying to build the ts files from the specs.

Error is : MyEnum is exported multiple times

### Expected result

Green build

**Comment by matthieu-crouzet** [comment]
swagger spec to reproduce the issue 
```yml
swagger: '2.0'
info:
  version: ''
  title: ''
paths: {}
definitions:
  _BaseModel:
    type: object
    required:
      - enumField
    properties:
      id:
        type: string
      enumField:
        type: string
        enum:
          - AAA
          - BBB
          - CCC
  'Model':
    type: object
    discriminator: enumField
    allOf:
      - $ref: '#/definitions/_BaseModel'
      - type: object
        discriminator: enumField
        required:
          - enumField
        properties:
          enumField:
            type: string
            enum:
              - AAA
              - BBB

**Comment by matthieu-crouzet** [comment]
It seems that `discriminator` in the sub schema is not necessary as already present in the `Model` schema.
```diff
swagger: '2.0'
info:
  version: ''
  title: ''
paths: {}
definitions:
  _BaseModel:
    type: object
    required:
      - enumField
    properties:
      id:
        type: string
      enumField:
        type: string
        enum:
          - AAA
          - BBB
          - CCC
  'Model':
    type: object
    discriminator: enumField
    allOf:
      - $ref: '#/definitions/_BaseModel'
      - type: object
-        discriminator: enumField
        required:
          - enumField
        properties:
          enumField:
            type: string
            enum:
              - AAA
              - BBB

**Comment by matthieu-crouzet** [comment]
I also want to raise the point that this swagger is not valid.
Following the documentation of [allOf](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/)

> allOf validates the value against all the subschemas

Here `_BaseModel` schema does not validate the other subschema in the `allOf`
