### ISSUE TITLE
[Bug]: Incorrect use of options in custom linter rules

### ISSUE THREAD

**Issue by cpaulve-1A** [AmadeusITGroup/otter#1161]
### Package name

eslint-plugin

### Package version

9.x

### Reproduction steps

Today, for typescript-eslint custom rules, we rely on the context.options when creating a new custom eslint rule. This is against the recommandation per eslint-typescript https://typescript-eslint.io/developers/custom-rules as it ignores the default values.

We should instead rely on the second parameter of the create function: options.
![image](https://github.com/AmadeusITGroup/otter/assets/110408057/f66a81de-3a5a-4140-a2bc-9f9d258a3352)

Note: we still rely on `@typescript-eslint/experimental-utils` while the package has been deprecated and will be remove in `@typescript-eslint` 6.x

### Current result

Use of context.options in all the otter ESLintUtils.RuleCreator 
![image](https://github.com/AmadeusITGroup/otter/assets/110408057/327b41d4-1e64-4509-b1e5-e8b0d3c8a1fb)

### Expected result

- [x] Use of `options` parameter

**Comment by matthieu-crouzet** [comment]
Usage of options has been done.
Using `@typescript-eslint/utils` is more complex than planned, as they dropped commonJS support.
