### ISSUE TITLE
[Bug]: Component with form - runtime replacement 

### ISSUE THREAD

**Issue by mrednic-1A** [AmadeusITGroup/otter#1168]
### Package name

components

### Package version

10.0.0-next

### Reproduction steps

on the latest version 10.0, in the showcase app, on the component replacement chapter, there is a hebrew flavor of date-picker.
Add a button which will switch the hebrew flavor with the default (gregorian) one via the config change. 
ref: [component replacement doc](https://github.com/AmadeusITGroup/otter/blob/main/docs/components/COMPONENT_REPLACEMENT.md#components-configuration)

### Current result

The components switch is ok, but there is an error for the propagation of the from control changes to the parent. It seems that the register function for 'onChanges' and 'onTouched' are not called by angular at a second initialialization (or switch) of a component via the c11n directive. (there is the error message in the console as ref)

### Expected result

The components to be switched and the changes from the form control propagated to the parent.
Keep the switch button into the showcase comp replacement page.

**Comment by pginoux-1A** [comment]
Fixed, it was linked to pnp and double angular version
