### ISSUE TITLE
[Feature]: Industrialization of Virtual Fs Testing

### ISSUE THREAD

**Issue by kpanot** [AmadeusITGroup/otter#1171]
### Context

In the @o3r/framework repository we use the `virtual-fs` helper provided by the internal `@o3r/test-helpers` package to emulate fs access.

The purpose of this task is to allow this feature when creation an Otter project (library / application) outside of Otter repository

### Proposal

- [ ] `Virtual-fs` should be exposed by published package (possibly `@o3r/testing`)
- [ ] The `ng-add` schematic should adding `fs` mock in jest setup file with explanation comment

### Links

- #1122

**Comment by pginoux-1A** [comment]
Blocked at this moment since we have no way of doing an installation on the file system
