### ISSUE TITLE
[Bug]: Localisation builders UTs are failing on CI

### ISSUE THREAD

**Issue by kpanot** [AmadeusITGroup/otter#1207]
### Package name

localization

### Package version

10.0.*

### Reproduction steps

Run skipped Localization's builders UTs.

### Current result

Instability of the UT based on Virtual Filesystem on Github CI (Linux and Windows)

### Expected result

UT to pass on CI

**Comment by fpaul-1A** [comment]
The tests have been re-enabled with PR https://github.com/AmadeusITGroup/otter/pull/1276
We should no longer have timeouts with the use of `advanceTimers: true` in fakeTimers config
