### ISSUE TITLE
import of `@typescript-eslint/utils` package instead of the `@typescript-eslint/experimental-utils` package

### ISSUE THREAD

**Issue by matthieu-crouzet** [AmadeusITGroup/otter#1224]

**Comment by kpanot** [comment]
If I understand well this change will result to:
- [ ] Migration of the Otter EsLint packages to ESM (type module)
- [ ] Migration of the eslintrc to `.mjs` in the different projects
- [ ] Provide `ng-update` schematic to the `eslint-config-otter` to apply this migration to Otter based projects

**Comment by fpaul-1A** [comment]
The import has been changed on main with PR #1500 , no need for ESM migration `@typescript-eslint/utils@7.3.1` is still using commonjs
