### ISSUE TITLE
[Feature]: SDK configuration to generate string instead of Date

### ISSUE THREAD

**Issue by matthieu-crouzet** [AmadeusITGroup/otter#1337]
### Context

As a developer, when I generate my SDK, I would like to have string instead of `Date` or `utils.Date` to handle it outside the SDK.

### Proposal

- [ ] Add a global flag for the generator cli
- [ ] Remove [comment](https://github.com/AmadeusITGroup/otter/pull/1331/files#diff-3fad1edb3d41e6d2684376caa467b073877a6ca8e96b132c64e4b380778e867fR639-R640)

**Comment by matthieu-crouzet** [comment]
https://github.com/AmadeusITGroup/otter/pull/1331/files#diff-3fad1edb3d41e6d2684376caa467b073877a6ca8e96b132c64e4b380778e867fR639-R640

**Comment by pginoux-1A** [comment]
As discussed this morning, this feature will be divided in 2 different tasks:
* First one is to support a parameter that will, as a default behavior, generate string for every dates from the specification
* Second one if to support either a format or a x-vendor in the specification to generate utils.Date when needed
