### ISSUE TITLE
[Bug]: IT test instability

### ISSUE THREAD

**Issue by kpanot** [AmadeusITGroup/otter#134]
### Package name

core

### Package version

8.*

### Reproduction steps

Create a PR without code change (can be documentation in docs/)

### Current result

Test_publish job is failing

### Expected result

Test_publish job to pass

**Comment by fpaul-1A** [comment]
Error still reproducing https://github.com/AmadeusITGroup/otter/actions/runs/4572801248/jobs/8072917126

**Comment by matthieu-crouzet** [comment]
maybe fixed by https://github.com/AmadeusITGroup/otter/commit/cccd1eaa37ef187d016fb8e29b4d576677ef0a4a

**Comment by mrednic-1A** [comment]
https://github.com/AmadeusITGroup/otter/actions/runs/5002768186/jobs/8963244512
random error on test-int

**Comment by kpanot** [comment]
Closing this issue thanks to refactor of the IT on Otter v10
