### ISSUE TITLE
[Bug]: Cache is not invalidate when a amasdk file pack has been updated

### ISSUE THREAD

**Issue by cpaulve-1A** [AmadeusITGroup/otter#1446]
### Package name

core, showcase-sdk swagger-builder

### Package version

10.0.0

### Reproduction steps

Build application as is. 
Once everything is build, modify the @ama-sdk/core file-pack cli script and rebuild the project.

### Current result

Showcase sdk is not rebuild even though it has a dependency on the @ama-sdk/core package

### Expected result

All the projects with a dependency on @ama-sdk/core should be rebuild.

**Comment by fpaul-1A** [comment]
Should be fixed by https://github.com/AmadeusITGroup/otter/pull/1457
