### ISSUE TITLE
[Bug]: Not all options accessible from configurationDevTools

### ISSUE THREAD

**Issue by rglearns** [AmadeusITGroup/otter#149]
### Package name

configuration

### Package version

8.0.x

### Reproduction steps

Activate the ConsoleDevTools Service and look at _OTTER_DEVTOOLS_

### Current result

The configurationDevTools is present but it does not have all properties (saveConfiguration for example)
![image](https://user-images.githubusercontent.com/42182287/222381766-22a82e2c-2335-462b-9c69-737f06bb1758.png)

### Expected result

All methods should be accessible via configurationDevTools if the service is activated

**Comment by kpanot** [comment]
The problem is because of the spread operator of the devkit services.
We try to spread the class properties to the `window.__OTTER_DEVTOOLS__` variable which is incorrect.
