### ISSUE TITLE
[Bug]: Required option '-i' is missing when running spec:regen

### ISSUE THREAD

**Issue by ADR-Clizy** [AmadeusITGroup/otter#1619]
### Package name

schematics

### Package version

10.1.1

### Reproduction steps

I created a SDK and failed relative path of my .yaml.

So in order to regen the spec, I copy paste my yaml in root sdk directory and renamed it as "swagger-spec.yaml".

Then I ran 

`npm run spec:regen --workspace=@irs/sdk`

### Current result

The output is : 

```
UPDATE swagger-spec.yaml (1988 bytes)
[error] Required option '-i' is missing
Error: OpenApiGeneratorCli failed to run OpenApiGenerator with command 'openapi-generator-cli generate --custom-generator=C:\embedded_insurance\irs-frontend\node_modules\@ama-sdk\schematics\schematics\typescript\core\openapi-codegen-typescript\target\typescriptFetch-openapi-generator.jar --generator-key irs-sdk'
npm ERR! Lifecycle script `generate` failed with error: 
npm ERR! Error: command failed
npm ERR!   in workspace: @irs/sdk@0.0.0-placeholder
npm ERR!   at location: C:\embedded_insurance\irs-frontend\libs\irs-sdk
npm ERR! Lifecycle script `spec:regen` failed with error: 
npm ERR! Error: command failed
npm ERR!   in workspace: @irs/sdk@0.0.0-placeholder
npm ERR!   at location: C:\embedded_insurance\irs-frontend\libs\irs-sdk
```

### Expected result

No Error

### Additional comments

I ran with the new swagger-spec.yaml : 

`npm run generate --workspace=@irs/sdk`

And it works but after, I tried to regen and had the same error as above.

**Comment by mrednic-1A** [comment]
Hi @ADR-Clizy ,
Thanks for your feedback.
We have tested the usecase using the 11.1 version of @ama-sdk/create, with a spec file coming from a relative path and with a spec file coming from an npm module. We could not reproduce the issue with spec:regen anymore. `npm run spec:regen` works in both cases.
In case we missed something with the reproduction, don;t hesitate to come back to us.
