### ISSUE TITLE
[Bug]: @o3r/workspace:application is generating a basic Angular Web App if app name includes an underscore

### ISSUE THREAD

**Issue by ADR-Clizy** [AmadeusITGroup/otter#1620]
### Package name

workspace

### Package version

10.1.1

### Reproduction steps

I tried to create an Angular app with o3r wrap with this command 

`npm exec ng g @o3r/workspace:application web_app`

### Current result

I have a classic Angular Web App as the output with following files / screen

```json
{
  "name": "web-app",
  "version": "0.0.0-placeholder",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~17.2.0",
    "@angular/common": "~17.2.0",
    "@angular/compiler": "~17.2.0",
    "@angular/core": "~17.2.0",
    "@angular/forms": "~17.2.0",
    "@angular/platform-browser": "~17.2.0",
    "@angular/platform-browser-dynamic": "~17.2.0",
    "@angular/router": "~17.2.0",
    "@design-factory/design-factory": "^17.1.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.3"
  },
  "devDependencies": {
    "@angular/cli": "~17.2.3",
    "@angular/compiler-cli": "~17.2.0",
    "typescript": "~5.3.2"
  }
}
```

```
$ ls
package.json  src/  tsconfig.app.json  tsconfig.spec.json
```

```
$ ls src/
app/  assets/  favicon.ico  index.html  main.ts  styles.scss
```

![image](https://github.com/AmadeusITGroup/otter/assets/93863257/b43f62e5-7dc7-4e19-9ce3-c3dab2e9b0fe)

### Expected result

I'm not sure if we expect a basic angular app when creating app with o3r framework

**Comment by kpanot** [comment]
Thank you @ADR-Clizy for your report.

Did you follow the document of the [Get Started](https://github.com/AmadeusITGroup/otter?tab=readme-ov-file#get-started) and execute the `npm create` command first?

In the context of the generated monorepo, the command `ng g @o3r/workspace:application` is, per default, supposed to generate a basic Angular application (represented in your screenshot) in the folder `apps`.

**Comment by ADR-Clizy** [comment]
Hello @kpanot :)

Yes I followed the Get Started doc and executed the npm create command first.

The issue comes from the name of the app in the following command.

`
npm exec ng g @o3r/workspace:application web_app
`

Output : 

![image](https://github.com/AmadeusITGroup/otter/assets/93863257/24e539f0-7a79-4a90-82ce-2f74282629ba)

But with this command 

`
npm exec ng g @o3r/workspace:application o3r-app
`


![image](https://github.com/AmadeusITGroup/otter/assets/93863257/c866cdc7-b58c-48b9-bd33-53f1b5ec3ea7)


It asks which preset to use etc so it comes from the "_" :/
