### ISSUE TITLE
[Feature]: Interface for ComponentIdentifier

### ISSUE THREAD

**Issue by mrednic-1A** [AmadeusITGroup/otter#1693]
### Context

There are several places in the framework wherethe type 
`{ library: string; name: string }` is used explicitly.

### Proposal

Create an interface for this type (Maybe ComponentIdentifier) and share it across framework. 
Maybe _@o3r/core_ is a good candidate of module where to define the interface.

**Comment by matthieu-crouzet** [comment]
I would propose `ItemIdentifier` as we have a method name `computeItemIdentifier` and we use this identifier for component and also configuration.
