### ISSUE TITLE
[Bug]: @o3r/localization  extractor skips objects

### ISSUE THREAD

**Issue by al-mart** [AmadeusITGroup/otter#1702]
### Package name

extractors

### Package version

9.3.10

### Reproduction steps

If i pass an object inside the transaltions.json as 
"a": {
  "b": "my message"
} 

I wait for it to be "a.b": "my message" as it is working fine in plain ngx-translate

### Current result

If i pass an object inside the transaltions.json as 
"a": {
  "b": "my message"
} 

I get "a": {}

### Expected result

I wait for it to be "a.b": "my message" as it is working fine in plain ngx-translate

**Comment by kpanot** [comment]
Hello @al-mart ,

Thank you for your report.
We can not really consider it as a bug as the format is defined in the following documentation :
https://github.com/AmadeusITGroup/otter/blob/main/docs/localization/LOCALIZATION.md#how-to-use

What can be improved is the documentation with the following items :
- [ ] Exposing the Json Schema of the `localization.json` in the `@o3r/localization` package
- [ ] Generating the `localization.json` file with the field `$schema` provided and targeting the schema

If you want to additionally support an "node structure" way to define the localization (which I think, it makes sense), I would encourage to open a [Feature Request](https://github.com/AmadeusITGroup/otter/issues/new?assignees=&labels=enhancement&projects=&template=5-FEATURE-FORM.yaml&title=%5BFeature%5D%3A+) with a similar the description.
