### ISSUE TITLE
[Feature]: Move clis from @ama-sdk/core to @ama-sdk/schematics

### ISSUE THREAD

**Issue by mrednic-1A** [AmadeusITGroup/otter#1843]
### Context

The 3 clis in **ama-sdk/core** are present in this package, but this one is meant to be used runtime in the application.

1. amasdk-clear-index 
2. amasdk-files-pack 
3. amasdk-update-spec-from-npm

### Proposal

As the **ama-sdk/schematics** is used for dev mode (generators) these clis should be moved here.
Also all the interfaces and constants used inside the generators declared in @ama-sdk/core should be moved in schematics.
https://github.com/AmadeusITGroup/otter/blob/main/packages/%40ama-sdk/core/src/fwk/open-api-tools-configuration.ts
https://github.com/AmadeusITGroup/otter/tree/main/packages/%40ama-sdk/core/src/utils/generators.ts

**Comment by kpanot** [comment]
Possible change to apply to `@ama-sdk/core` package after the move:
- removal of the dependency to `minimist` and `chokibar`
- removal of the file `open-api-tools-configuration.ts`
