### ISSUE TITLE
[Bug]: `ng add @o3r/testing` is adding the `jest` dependencies with the version `latest`

### ISSUE THREAD

**Issue by kpanot** [AmadeusITGroup/otter#1902]
### Package name

testing

### Package version

10.0.0+

### Reproduction steps

Create a new application with

```shell
npm create @o3r my-project
cd my-project
npm exec ng g application my-app
```

Add the `@o3r/testing` package:
```shell
npm exec ng add @o3r/testing --project-name my-app
```

### Current result

The dependencies to Jest have been added with the versions `latest`.

### Expected result

The versions of the Jest dependencies should be added aligned with the versions specified in the `@o3r/testing` dependencies.

**Comment by vscaiceanu-1a** [comment]
fixed in #1903
