### ISSUE TITLE
[Feature]: Review and cleanup eslint-config 

### ISSUE THREAD

**Issue by cpaulve-1A** [AmadeusITGroup/otter#2052]
### Context

**Pre-requisite**
- Decision around the use of prettier to be taken.

**Context**
The current eslint-config list many deprecated rules that could be migrated from eslint/typescript-eslint to typescript-eslint and stylistics.
Non exhaustive list contains the following:
- comma-dangle
- comma-style
- dot-location
- eol-last
- indent
- key-spacing
- linebreak-style
- max-length
- new-parens
- no-mixed-spaces-and-tabs
- no-multiple-empty-lines
- no-multi-spaces
- no-trailing-spaces
- quotes
- semi
- spaced-comment
- space-in-parens
- space-unary-ops

### Proposal

Review all the current eslint rules.
Depending on the decision about the usage of prettier, replace them with their supported equivalent (typescript-eslint or stylistics) rules or remove them, if they are duplicates of prettier config.

**Comment by cpaulve-1A** [comment]
Note that we should not just cover the stylistic rules but all the deprecated eslint rules (eg. eslint id-blacklist has been replaced with id-denylist)

**Comment by guillaumerochelle** [comment]
Hello,

[stylistics.cjs](https://github.com/AmadeusITGroup/otter/blob/0ffdab5b21d7c8580834d5c4f5486bd147ae6cc1/packages/%40o3r/eslint-config-otter/rules/typescript/stylistic.cjs#L5) is using `@stylistics/eslint-plugin-ts`.

I think it would be better to use `@stylistic/eslint-plugin`, according to the docs (extract below):
> Stylistic rules for ESLint, works for both JavaScript, TypeScript and JSX.
>
> This plugin provides all rules from:
>
>    [@stylistic/eslint-plugin-js](https://eslint.style/packages/js)
>    [@stylistic/eslint-plugin-ts](https://eslint.style/packages/ts)
>    [@stylistic/eslint-plugin-jsx](https://eslint.style/packages/jsx)
>    [@stylistic/eslint-plugin-plus](https://eslint.style/packages/plus)
>
> With this plugin, **you no longer need to mainly disable JavaScript in favor of TypeScript. Rules work for both languages.**

And in the ["Project progress" page](https://eslint.style/contribute/project-progress), it is mentioned that JS/TS/JSX packages will be deprecated in the future.
> 👉 Fuse JS/TS/JSX rules into a single package, and merge their docs. After this, separate packages for JS/TS/JSX will be deprecated.
