### ISSUE TITLE
[Bug]: Coverage reporting not working for Integration tests

### ISSUE THREAD

**Issue by kpanot** [AmadeusITGroup/otter#2455]
### Package name

- global -

### Package version

*

### Reproduction steps

Publish IT Coverage report to CodeCov

### Current result

Raising error

### Expected result

Be correctly published

**Comment by fpaul-1A** [comment]
Can we ever have this working?
The it-tests don't run on source code but on artifacts publish on verdaccio, I don't think the coverage can apply here.

**Comment by kpanot** [comment]
Indeed, let's abort Coverage for IT for now
