### ISSUE TITLE
Broken link for Otter team in readme

### ISSUE THREAD

**Issue by vscaiceanu-1a** [AmadeusITGroup/otter#25]
In the `readme.md`, the link for the Otter team is incorrect. It currently directs to https://github.com/orgs/amadeus-digital/teams/otter, but it should be https://github.com/orgs/AmadeusITGroup/teams/otter_admins.

**Comment by kpanot** [comment]
The link you mentioned is not accessible for people outside of AmadeusITGroup organization.
Maybe a mention via @AmadeusITGroup/otter_admins it is?
