### ISSUE TITLE
[Bug]: shareReplay keeps cached value in memory

### ISSUE THREAD

**Issue by ntrotner** [AmadeusITGroup/otter#2509]
### Package name

configuration, localization

### Package version

10.2

### Reproduction steps

Use the translation pipe or function often in the app

### Current result

Translation results are kept in memory even though they have no one that is observing them

### Expected result

Memory should be cleaned up :)

### Additional comments

We had been running into some issues in regards to memory consumption and in the traces I have found that lots of objects were related to translations. For about 6 months I had overridden the `translate` function from `LocalizationService` with the addition of the `refCount: true` to `shareReplay`. As a result we observed a drop of memory usage (when using our app in a long flow), specifically for the OperatorSubscriber (that is used internally by the `shareReplay` to keep the value "alive").

(Value on the left with `x22170` and `x77596` are the amount of objects retained and the rightmost value indicated the retained size in bytes)
Before override:
![Screenshot 2024-11-25 at 09 14 13](https://github.com/user-attachments/assets/40afc309-de59-4c15-9805-4e366aee4913)

After override:
![Screenshot 2024-11-25 at 09 14 37](https://github.com/user-attachments/assets/a551e272-1d63-4f15-bc56-f87a67a2e35e)

Functionally speaking we have not observed any bugs in these months, so for the translate change I'm very confident to apply that change. For the configuration I've seen that some more `shareReplay(1)` exist, their footprint is minimal since we call them once per component, therefore they are almost negligible. However I think they should be cleaned up as well when a component is no longer observing these values. There are some more occurences of this type of caching in the code, but I didn't check if they could benefit us.

**Comment by kpanot** [comment]
Hi,

Thank you for the contribution.
I close this issue as your PR #2510  is merged on `release/11.4`.
