### ISSUE TITLE
[Feature]: More flexible peer deps version ranges

### ISSUE THREAD

**Issue by mrednic-1A** [AmadeusITGroup/otter#2547]
### Context

Today the peer dependencies we are setting for the packages are using `~` so we allow only patches to be compatible. 
This is raising a lot of warnings for yarn package manager (errors for npm) if a peer dep is not matching the minor version.

### Proposal

-Use ^ instead of ~  (since there are no breaking changes between minors)
-Impose patch version 0 (example: ^2.4.0 instead of ^2.4.9)
-Update of minor versions in the peer dependencies by hand when needed

**Comment by kpanot** [comment]
I would disagree with the 2 last points which are not aligned with the output of the Otter Discussion:

> -Impose patch version 0 (example: ^2.4.0 instead of ^2.4.9)

I agree that patch version to `0` should be the default value when updating to new minor/major but it should not be "imposed".
In case of mandatory bugfix to propagate, the patch version may need to be upgraded (potentially manually).
This point has been discussed and agreed in Otter Discussion.

> -Update of minor versions in the peer dependencies by hand when needed

Nop, the upgrade of minor version should be part of the automatic upgrade process to align the `devDependencies` (targeting the latest major/minor version) used in our development and , more important, our tests with the `peerDependencies`.
This point has already been discussed and agreed in Otter Discussions.
