### ISSUE TITLE
[Bug]: Rules engine - actions not reset when no rulesets remains activated

### ISSUE THREAD

**Issue by mrednic-1A** [AmadeusITGroup/otter#2609]
### Package name

rules-engine

### Package version

10.4.*

### Reproduction steps

Have a ruleset with only one rule driven by a linked component (a page).
The success element is a change of localization key. This key should be used in a component which is visible when navigating through the app (the header component is a good option).
Navigate to the page where the ruleset becomes active -> the localization key is changed
Leave that page -> the localization key is still changed

### Current result

The localization key updated by the rules engine is not reset when the ruleset becomes inactive, the localizationOverride store is containing the loc keys change.

### Expected result

The localization key should be reset when the ruleset becomes inactive

**Comment by matthieu-crouzet** [comment]
Fixed by https://github.com/AmadeusITGroup/otter/pull/2610
