### ISSUE TITLE
Fixed default Github changelog template

### ISSUE THREAD

**Issue by kpanot** [AmadeusITGroup/otter#268]
### **Context**:
When creating a new release, Github provide a feature to generate the changelog based on the commit messages.
The issue is that the list of changes is ordered following based on the commit creation date.

### **Proposal**:
As our commit messages are following the commitlint standard pattern, we would be able to regroup the change messages according to their prefix.
It would be more readable to regroup the different change according.
(bonus: pointing out the commit flagged as including breaking change)

**Comment by matthieu-crouzet** [comment]
[More info](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes)
