### ISSUE TITLE
[Bug]: Localized currency pipe signatures

### ISSUE THREAD

**Issue by mrednic-1A** [AmadeusITGroup/otter#293]
### Package name

localization

### Package version

8.1.1

### Reproduction steps

Localized currency pipe extends angular currency pipe but at transpilation we lose the third signature.
The implementation is correct having the 3 signatures
https://github.com/AmadeusITGroup/otter/blob/main/packages/%40o3r/localization/src/tools/localized-currency.pipe.ts#L28

### Current result

At transpilation the third signature is removed from the d.ts file

    /**
     * @inheritdoc
     */
    transform(value: number | string, currencyCode?: string, display?: 'code' | 'symbol' | 'symbol-narrow' | string | boolean, digitsInfo?: string, locale?: string): string | null;
    transform(value: null | undefined, currencyCode?: string, display?: 'code' | 'symbol' | 'symbol-narrow' | string | boolean, digitsInfo?: string, locale?: string): null;
    ngOnDestroy(): void;
    ...

### Expected result

to have the 3rd signature in the types, as the extended angular currency pipe has.
```
 transform(value: number | string, currencyCode?: string, display?: 'code' | 'symbol' | 'symbol-narrow' | string | boolean, digitsInfo?: string, locale?: string): string | null;
 transform(value: null | undefined, currencyCode?: string, display?: 'code' | 'symbol' | 'symbol-narrow' | string | boolean, digitsInfo?: string, locale?: string): null;
 transform(value: number | string | null | undefined, currencyCode?: string, display?: 'code' | 'symbol' | 'symbol-narrow' | string | boolean, digitsInfo?: string, locale?: string): string | null;
    static ɵfac: i0.ɵɵFactoryDeclaration<CurrencyPipe, never>;
...
```

**Comment by kpanot** [comment]
What is the issue relative of having only 2 of the 3 function overload in this .d.ts file?
Because I think it is because of extending the `CurrencyPipe` that provides this function interface
