### ISSUE TITLE
Support multi projects angular repository

### ISSUE THREAD

**Issue by kpanot** [AmadeusITGroup/otter#358]
## Context

Today our schematics (`ng add` included) are required to be run on one specific project of an Angular repository.
An Angular repository can be composed of several projects (applications and/or library).
In our current implementation, as only one project is considered, the first one is taken as default.

## Proposal

- Determine which schematics should be apply to Application, Library or Both
- Determine if the schematic require to target only one project (and then turn this project parameter as mandatory)
- Fix the schematics that should be applied to all the projects (according to their type?) of the repository
- Deprecate the `getProjectFromTree` function to turn the project name to mandatory parameter

**Comment by kpanot** [comment]
Requires #357

**Comment by mrednic-1A** [comment]
Requires #633
