### ISSUE TITLE
Build the Otter VScode Extension with webpack

### ISSUE THREAD

**Issue by kpanot** [AmadeusITGroup/otter#362]
## Context

Today, the VSCode Extension is only transpiled using TSC build.
The problem of it is that the dependencies of the VScode extension package are not embedded in final JS Code which is restricting the package to only type devDependencies.

## Proposal

Use Webback to build the application and embed its external dependencies.

**Comment by sdo-1A** [comment]
@kpanot We now use esbuild, can we close this issue?
