### ISSUE TITLE
Promote Otter VsCode Extension and Chrome Devtools

### ISSUE THREAD

**Issue by kpanot** [AmadeusITGroup/otter#52]
**Context**:
Currently the Otter Chrome extension and VsCode extension are both published to their respective stores.
The purpose of this task is to help user to find it.

**Actions**:
 - [x] To promote the VsCode extension, the `@o3r/core` schematics of `ng add` and `ng update` should add the `AmadeusITGroup.otter-devtools` extension into the `recommendations` list of the `extensions.json` file.
 - [x] To promote the Otter Chrome Devtools, the link of the extension can be displayed in the console in the end of the `ng add` schematics of the following packages: `@o3r/localization`, `@o3r/testing`, `@o3r/rules-engine` and `@o3r/application`
 - [ ] #67

**Comment by matthieu-crouzet** [comment]
To promote the Otter Chrome Devtools, we can display the link in the console as you propose but also add a question in the schematics to add the code to activate service in the app for the extension

**Comment by kpanot** [comment]
Created task to handle the add of the debug toolings
