### ISSUE TITLE
[Bug]: Cannot read properties of undefined , Reading escapedName

### ISSUE THREAD

**Issue by rglearns** [AmadeusITGroup/otter#524]
### Package name

components

### Package version

8.2.x

### Reproduction steps

Have a config that references  string literals via an exported type as below 
```typescript
 export type MyType = 'value1' | 'value2'

export interface MyConfig extends Configuration {
myConfigAttr: MyType[]
}
export MyConfigValue : MyConfig {
myConfigAttr: 'value1'
}
```
when trying to run the config extractor, the extractor fails

### Current result

The error in the issue title is raised

### Expected result

The extractor should run successfully 

### Additional comments

On debugging the issue comes from 
https://github.com/AmadeusITGroup/otter/blob/66b565a8e35312c37299788c629c9ff0782701ec/packages/%40o3r/components/builders/component-extractor/helpers/component/component-config.extractor.ts#L165
where type does not have symbol but aliasSymbol instead 

So changing the above to 
```typescript
          const symbolName = this.getSymbolName(type.symbol || type.aliasSymbol);
```
seems to fix it

**Comment by kpanot** [comment]
Thank you for the investigation.
A Pull Request has been opened following your suiggestion
