### ISSUE TITLE
Convert version-harmonize to Yarn Plugin

### ISSUE THREAD

**Issue by kpanot** [AmadeusITGroup/otter#599]
### Context

The version-harmonize tool, provided by `@o3r/dev-tools`, is aligning the versions of the different package's dependencies of the workspaces.
To be able to simplify and automatize the usage of the version harmonization (that can be done at the installation time), the version harmonize can be provided as yarn plugin.

### Proposal

Expose the version-harmonize script as [yarn plugin](https://yarnpkg.com/features/plugins).
The script may requires to have it own package

**Links**:
- [Writing our first plugin](https://yarnpkg.com/advanced/plugin-tutorial#writing-our-first-plugin)

**Comment by vscaiceanu-1a** [comment]
Does this mean that our `npm` users won't be able to benefit from the version harmoniser?

**Comment by kpanot** [comment]
The purpose is not to dedicated the feature to yarn only, but to expose the interface for a yarn plugin

**Comment by kpanot** [comment]
Actually a good compromise could be to expose to version harmonize as ESLint rule
