### ISSUE TITLE
o3r/testing - to setup the testing framework

### ISSUE THREAD

**Issue by mrednic-1A** [AmadeusITGroup/otter#602]
### Context

Today when we execute **ng add of o3r/core** we ask the user which testing framework is using (_jest/jasmine_) and we do the modification of _ts.config.spec.json_ with the specific paths in the compiler property.

### Proposal

We want to take the modularity approach and to move this part from _o3r/core to o3r/testing_.
The idea is to run the `**ng add @o3r/testing**` and to have a prompt to select the testing framework:
- there will be 2 options:
     - jest
     - other
     
If **jest** is selected then the testing setup will be done on the project depending on where the ng add was run.
- at monorepo level - will add jest dependencies, setup jest config and tsconfig files
- same in a lib/application (dependencies and config files)   
If **other** is selected, then nothing will be done to setup the testing framework.

Other updates done today by the ng add of o3r/testing or o3r/core (related to testing) will be kept (or moved to o3r/testing if they are done in o3r/core)
- playwright will be handled by another enhancement.

**Comment by vscaiceanu-1a** [comment]
Playwright part will be handled in https://github.com/AmadeusITGroup/otter/issues/657
