### ISSUE TITLE
[Bug]: Custom mat form field control is broken when decorated by the O3rComponent decorator post v9.0

### ISSUE THREAD

**Issue by Abhirocks889** [AmadeusITGroup/otter#607]
### Package name

core

### Package version

9.0.2

### Reproduction steps

Decorate any custom mat form field control component with the `O3rComponent` decorator from `o3r/core`. It results in the `MatFormFieldClass` being unable to identify the custom control and thereby, a runtime error like the one shown below.

![image](https://github.com/AmadeusITGroup/otter/assets/15943209/4b3e0aed-586f-49c8-8e63-31a17e3f3eef)

For minimal reproduction, I have created a simple repository that highlights the issue:
https://github.com/Abhirocks889/CustomFormFieldControl

### Current result

The material form field class script execution fails with an error and hence, all the error handling, validation and other features are lost pertaining to the custom form field control.

### Expected result

The custom form field control should work as expected without any runtime errors.

### Additional comments

The obvious workaround is to avoid decorating the custom form field control components with the concerned decorator.

**Comment by matthieu-crouzet** [comment]
Thank you for the reproduction repository
It seems that with non-legacy module from material + using 
```typescript
providers: [{
    provide: MatFormFieldControl,
    useExisting: forwardRef(() => DoubleInputFormComponent)
}]
  ```
  in your component decorator fix your issue
  (`forwardRef` comes from `@angular/core`)
