### ISSUE TITLE
[Feature]: Check alignment of config interface name and first param of computeConfigurationName

### ISSUE THREAD

**Issue by guillaumerochelle** [AmadeusITGroup/otter#625]
### Context

When using component extractor from @o3r/components, it is possible to have discrepancies between the actual configuration id of a component and what is extracted in the component.config.metadata.json file.

For example, with this config.ts:
```typescript
export interface MyComponentConfig extends Configuration {
  // omitted
}

// Note the discrepancy here between MyComponentConfig and AnotherConfig
export const MY_COMPONENT_CONFIG_ID = computeConfigurationName('AnotherConfig', '@myscope/components');
```

The resulting component.config.metadata.json:
```
[
  {
    "library": "@myscope/components",
    "name": "MyComponentConfig", // <-- The real config id in the code is : @myscope/components#AnotherConfig
    "path": "(...)",
    "type": "COMPONENT",
    "properties": []
  }
]
```

### Proposal

As a user of component extractor, I would like the builder to compare the interface name and the first param of `computeConfigurationName` to make sure they are aligned during the extraction.

**Comment by kpanot** [comment]
Actually the fact to have a constant suffixed by `_CONFIG_ID` (or using the `computeConfigurationName` function) is not mandatory and should not be parsed by the configuration extractor.
This constant is generated only to simplify the retrieve of the configuration by the associated component, I do not think it is the job the extractor to check the values of this constant (or even checking the fact that there is no multiple constants).

For me what you are requesting sounds like a EsLint Plugin that could be exposed by the `@o3r/configuration` package.
