### ISSUE TITLE
Add logs on O3rElements

### ISSUE THREAD

**Issue by cpaulve-1A** [AmadeusITGroup/otter#65]
Playwright Locator seems more restrictive than ElementHandler, it could be worth to add some logs on some errors thrown to ease the e2e testing

**Comment by kpanot** [comment]
This may be linked to the internal User Story relative to logging: https://dev.azure.com/AmadeusDigitalAirline/Otter/_backlogs/backlog/Otter%20Scrum%20Board/Stories/?workitem=1286
