### ISSUE TITLE
[Bug]: A PR from a fork can not add labels

### ISSUE THREAD

**Issue by kpanot** [AmadeusITGroup/otter#711]
### Package name

build-helpers

### Package version

9.0.0+

### Reproduction steps

Create a pull request from a fork, containing a commit with the following commit message `fix: label reporting in pull request`.

### Current result

The list of labels are correctly calculated but not correctly reported using the GH API (because of the lack of access of the user token).

*Example:*
- https://github.com/AmadeusITGroup/otter/actions/runs/6025998539/job/16347965744?pr=705

### Expected result

report the following labels `bugfix` and `project:@o3r/build-helpers`.

**Comment by pginoux-1A** [comment]
Possible solutions
* Workflow run
* GitHubApp (more costly)

**Comment by kpanot** [comment]
The usage of `workflow_run` maybe a solution be complicated to put in place for the following reasons:
- NX Diff tool needs to work over 2 remotes (base and target)
- The `workflow_run` can not take parameters (mainly the **PR ID** for label reporting and the **label list**)

**Comment by fpaul-1A** [comment]
> The usage of `workflow_run` may be a solution complicated to put in place for the following reasons:
> 
> * NX Diff tool needs to work over 2 remotes (base and target)
> * The `workflow_run` can not take parameters (mainly the **PR ID** for label reporting and the **label list**)

One solution can be to run the label computation on the main workflow of the PR and upload an artifact containing them (instead of trying to update the PR right away).
Then we can use a workflow_run to read this artifact and update the tags on the pull_request
