### ISSUE TITLE
[Bug]: `npm create @o3r` fails + no arguments forwarded to ng add o3r/core 

### ISSUE THREAD

**Issue by mrednic-1A** [AmadeusITGroup/otter#723]
### Package name

create

### Package version

9.2.0-alpha.44

### Reproduction steps

npm create @o3r my-workspace --no-enable-customization

### Current result

unknown option enableCustomization

### Expected result

workspace created and the option passed taken into consideration for the `ng add` of `o3r core`

### Additional comments
Use case is to run the `o3r create` passing the arguments on command line, not interactive mode.

The comand is failing because the argument is passed to `ng new` command ( to the angular generator) which is called by o3r create.
A possible solution is to filter the arguments and remove the options not taken by the `ng new`.

Also, the arguments passed in the command line should be forwarded to `ng add @o3r/core`.

**Comment by kpanot** [comment]
Incorrect Reproduce steps, the correct one is:
`npm create https://github.com/o3r my-workspace -- --no-enable-customization`
