### ISSUE TITLE
[Bug]: `npm create @o3r my-workspace` create a commit before o3r is added

### ISSUE THREAD

**Issue by matthieu-crouzet** [AmadeusITGroup/otter#736]
### Package name

create

### Package version

9.1

### Reproduction steps

`npm create @o3r my-workspace`

### Current result

Repository is initialized with one commit that contains only the angular part, not the @o3r/core part.
The @o3r/core part is not committed.

### Expected result

1 initial commit with everything inside
or 2 commits, one for the angular/nx part and one for the add of @o3r/core

### Additional comments

Bonus: support the option `--skip-git`, as angular and nx.

**Comment by kpanot** [comment]
It looks more to feature than a bug.

**Comment by matthieu-crouzet** [comment]
For me it's a bug that you have uncommitted file after the 'create'
