### ISSUE TITLE
[Feature]: IT for o3r create

### ISSUE THREAD

**Issue by mrednic-1A** [AmadeusITGroup/otter#745]
### Context

The goal of this feature is to capture the early issues we could have with the execution of the create command for the `o3r` framework.

### Proposal

Create an integration test which will run the **o3r create** command, across test matrix contexts (windows npm, windows yarn ...)

Pass command line arguments:
- one to the angular generator 
- another argument to the _ng add o3r/core_. 
The goal is to test that the cmd line arguments are well forwarded

**Comment by kpanot** [comment]
Duplicate of #1228
