### ISSUE TITLE
[Feature]: Transpose the VS Code extension into a WebStorm Plugin

### ISSUE THREAD

**Issue by OxyFlax** [AmadeusITGroup/otter#798]
### Context

There's a great extension built for VS Code but many people across or organisation are using WebStorm and it would be nice to get the same features.
Additional context, WebStorm >>> VS Code 😜 

### Proposal

Build a plugin for WebStorm with same functionalities as the VS Code extension.

**Comment by kpanot** [comment]
duplicate of #799
