### ISSUE TITLE
[Bug]: o3r generator core component dependency error after execution

### ISSUE THREAD

**Issue by OxyFlax** [AmadeusITGroup/otter#821]
### Package name

core, schematics

### Package version

9.0.3

### Reproduction steps

Repo with these as dependencies:
```
"@o3r/apis-manager": "~9.0.3",
"@o3r/components": "~9.0.3",
"@o3r/configuration": "~9.0.3",
"@o3r/core": "~9.0.3",
"@o3r/dynamic-content": "~9.0.3",
"@o3r/eslint-config-otter": "~9.0.3",
"@o3r/eslint-plugin": "~9.0.3",
"@o3r/localization": "~9.0.3",
"@o3r/logger": "~9.0.3",
"@o3r/routing": "~9.0.3",
"@o3r/rules-engine": "~9.0.3",
"@o3r/styling": "~9.0.3",
"@o3r/testing": "^9.1.2",
```

And these as devDependencies:
```
"@o3r/dev-tools": "^9.0.3",
"@o3r/extractors": "~9.0.3",
"@o3r/stylelint-plugin": "~9.0.3",
```

Run the following command:
`ng generate @o3r/core:component`

### Current result

It's requiring packages `@angular-devkit/schematics` and `@schematics/angular` and gives error before using it (I assume this is normal - but not sure if normal that we need to include them explicitly in our package.json - I would assume this would be installed along with the associated o3r package, I might be wrong).

Actual error: after adding those 2 and running the schematic, it asks me all questions for the schematic but after completing the questions it gives an error that o3r/schematics is required.

### Expected result

I would expect the error to come before the different questions, like for the other packages.

**Comment by kpanot** [comment]
This is the normal behaviour from Angular Schematics mechanism:
The questions are asked before the JS code (of the schematic implementation) has been run.

Regarding your missing dependencies, the ones you mentioned are part of the peerDependencies of the `@o3r/eslint-config` package so the warning should have been raised by you NPM client regarding this missinh packages.

**Comment by OxyFlax** [comment]
Ok thanks I thought all would pop up at the same time
