### ISSUE TITLE
[Bug]: sdk create with yarn

### ISSUE THREAD

**Issue by mrednic-1A** [AmadeusITGroup/otter#940]
### Package name

@ama-sdk/schematics

### Package version

9.2

### Reproduction steps

generate an sdk-shell repo

`yarn create @ama-sdk typescript sdk-name`

### Current result

the shell files are created;
a _.yarnrc.yml_ file is created but there is no yarn version specified, neither a _.yarn/releases_ folder created to have the version of yarn fixed inside the repository.
This might be a regression from the old package (generator-sdk)

### Expected result

to have yarn locally inside the generated repository for the sdk.

**Comment by kpanot** [comment]
I guess that a solution would be to run `yarn set version ${generatorPackageJson.packageManager.split('@')?.[1] || 'latest'}` ?
